CREATE TYPE public.categories AS ENUM (
  'sport-shoes'
);

CREATE TABLE public.products (
  product_id BIGINT PRIMARY KEY generated by DEFAULT AS IDENTITY NOT NULL,
  sku VARCHAR(255) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL UNIQUE,
  slug VARCHAR(120) NOT NULL UNIQUE,
  category public.categories NOT NULL,
  img TEXT,
  numOfColors INT NOT NULL,
  price MONEY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  modified_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

INSERT INTO public.products (sku, title, slug, category, img, numOfColors, price) VALUES('100', 'NikeCourt Tech Challenge 20', 'tech-challenge', 'sport-shoes', 'tech-challenge', 2, 165.00), 
('101', 'Nike Metcon 5 AMP', 'metcon-5', 'sport-shoes', 'metcon-5', 1, 165.00),
('102', 'Nike Phantom Vision', 'phantom', 'sport-shoes', 'phantom', 4, 165.00),
('103', 'Nike Air Zoom Pegasus', 'pegasus', 'sport-shoes', 'pegasus', 1, 165.00),
('104', 'Nike Joyride Dual Run', 'joyride', 'sport-shoes', 'joyride', 2, 170.00),
('105', 'Nike Tiempo Legend 8', 'legend-academy', 'sport-shoes', 'legend-academy', 8, 165.00),
('106', 'Nike React Infinity Pro', 'react-infinity', 'sport-shoes', 'react-infinity', 1, 160.00),
('107', 'Nike React Phantom Run Flyknit 2', 'phantom-flyknit', 'sport-shoes', 'phantom-flyknit', 4, 185.00),
('108', 'LeBron 17', 'lebron', 'sport-shoes', 'lebron', 1, 260.00);
