const SHOES = [
  {
    slug: 'tech-challenge',
    name: 'NikeCourt Tech Challenge 20',
    sku: 100,
    category: "sport shoes",
    imageSrc: '/assets/tech-challenge.webp',
    price: 165.00,
    numOfColors: 2,
  },
  {
    slug: 'metcon-5',
    name: 'Nike Metcon 5 AMP',
    sku: 101,
    category: "sport shoes",
    imageSrc: '/assets/metcon-5.webp',
    price: 165.00,
    numOfColors: 1,
  },
  {
    slug: 'phantom',
    name: 'Nike Phantom Vision',
    sku: 102,
    category: "sport shoes",
    imageSrc: '/assets/phantom.webp',
    price: 165.00,
    numOfColors: 4,
  },
  {
    slug: 'pegasus',
    name: 'Nike Air Zoom Pegasus',
    sku: 103,
    category: "sport shoes",
    imageSrc: '/assets/pegasus.webp',
    price: 165.00,
    numOfColors: 1,
  },
  {
    slug: 'joyride',
    name: 'Nike Joyride Dual Run',
    sku: 104,
    category: "sport shoes",
    imageSrc: '/assets/joyride.webp',
    price: 170.00,
    numOfColors: 2,
  },
  {
    slug: 'legend-academy',
    name: 'Nike Tiempo Legend 8',
    sku: 105,
    category: "sport shoes",
    imageSrc: '/assets/legend-academy.webp',
    price: 16500,
    numOfColors: 8,
  },
  {
    slug: 'react-infinity',
    name: 'Nike React Infinity Pro',
    sku: 106,
    category: "sport shoes",
    imageSrc: '/assets/react-infinity.webp',
    price: 16000,
    numOfColors: 1,
  },
  {
    slug: 'phantom-flyknit',
    name: 'Nike React Phantom Run Flyknit 2',
    sku: 107,
    category: "sport shoes",
    imageSrc: '/assets/phantom-flyknit.webp',
    price: 18500,
    numOfColors: 4,
  },
  {
    slug: 'lebron',
    name: 'LeBron 17',
    sku: 108,
    category: "sport shoes",
    imageSrc: '/assets/lebron.webp',
    price: 26000,
    numOfColors: 1,
  },
];

export default SHOES;